# -*- coding: utf-8 -*-
"""Seasonal_Agriculture_Performance_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uRCsvcDih9NPnMemdK2-s1RwwXSwmQgi
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/seasonal_agriculture_performance_dataset.csv")

df.head()

df.tail()

df.shape

df.info()

df.describe()

df.dtypes

df.isnull().sum() #checking null values

print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

print("\nColumn Names:")
print(df.columns.tolist())

df.hist(bins=15,figsize=(10,10))

df.info()

df.describe(include='all').T

missing_values = df.isnull().sum()

missing_values = missing_values[missing_values > 0].sort_values(ascending=False)

print("Missing values in each column:")
print(missing_values)

print("Number of duplicate rows:", df.duplicated().sum())

df = df.drop_duplicates()

print("Dataset shape after removing duplicates:", df.shape)

categorical_columns = df.select_dtypes(include='object').columns.tolist()
numerical_columns = df.select_dtypes(include=np.number).columns.tolist()

print("Categorical Columns:")
print(categorical_columns)

print("\nNumerical Columns:")
print(numerical_columns)

for col in categorical_columns:
    print(f"\n{col}:")
    print(df[col].value_counts().head(20))

season_counts = df['Season'].value_counts()

print(season_counts)

plt.figure(figsize=(8,5))

sns.countplot(data=df, x='Season')

plt.title('Distribution of Agricultural Records Across Seasons')
plt.xlabel('Season')
plt.ylabel('Number of Records')

plt.show()

seasonal_performance = df.groupby('Season')['Yield_Tonnes_Ha'].agg(
    ['count', 'mean', 'median', 'min', 'max', 'std']
)

seasonal_performance

print("Columns in DataFrame:")
for col in df.columns:
    print(repr(col))

plt.figure(figsize=(9,5))

sns.barplot(
    data=df,
    x='Season',
    y='Yield_Tonnes_Ha',
    estimator='mean',
    errorbar=None
)

plt.title('Average Agricultural Performance Across Seasons')
plt.xlabel('Season')
plt.ylabel('Average Crop Yield')

plt.show()

print("Number of duplicate rows:", df.duplicated().sum())

categorical_columns = df.select_dtypes(include='object').columns.tolist()
numerical_columns = df.select_dtypes(include=np.number).columns.tolist()

print("Categorical Columns:")
print(categorical_columns)

print("\nNumerical Columns:")
print(numerical_columns)

season_counts = df['Season'].value_counts()

print(season_counts)

plt.figure(figsize=(10,6))

sns.boxplot(
    data=df,
    x='Season',
    y='Crop'
)

plt.title('Detection of Possible Seasonal Performance Outliers')
plt.xlabel('Season')
plt.ylabel('Yield_Tonnes_Ha')

plt.show()

seasonal_resource = df.groupby('Season')['Water_Used_m3'].mean().sort_values(ascending=False)

print(seasonal_resource)

crop_season = pd.pivot_table(
    df,
    values='Farm_Area_Hectares',
    index='Crop',
    columns='Season',

)

crop_season

plt.figure(figsize=(12,6))

sns.barplot(
    data=df,
    x='Crop',
    y='Farm_Area_Hectares',
    hue='Season',
    errorbar=None
)

plt.title('Crop Performance Across Different Seasons')
plt.xlabel('Crop')
plt.ylabel('Average Crop Yield')
plt.xticks(rotation=45)

plt.show()

plt.figure(figsize=(8,6))

sns.scatterplot(
    data=df,
    x='Water_Used_m3',
    y='Crop',
    hue='Season'
)

plt.title('Relationship Between Water_Used and Crop')
plt.xlabel('Water_Used_m3')
plt.ylabel('Crop')

plt.show()

